### ISSUE TITLE
Workflow broke upon upgrading to Yosemite

### ISSUE THREAD

**Issue by mclowe-directnic** [eusi/alfred2-twitch-streamer#2]
After upgrading to Yosemite, there seems to be a problem with this workflow.

It seems that the function imagepng in search.php (line 221) is undefined after the upgrade. Skipping this call and making the function resizeImageAndConvertToPNG return true at the very beginning seems to have fixed the workflow for me.

**Comment by eusi** [comment]
After a while I came back to this issue and created version 1.6 which doesn't use GD library. It creates JPG files instead of PNG.

This is not and an upgrade. If you could build the new homebrew and so make v1.52 work, so you dont't have to change to 1.6. Otherwise 1.6 should run in any way.
