### ISSUE TITLE
twgames breaking with Alfred 3

### ISSUE THREAD

**Issue by pedrokleiz** [eusi/alfred2-twitch-streamer#5]
Hi,
I just found out that with Alfred 3 that selecting a game with **twgames** just stops Alfred as a whole. Do you have any idea why it's happening like that?

**Comment by eusi** [comment]
Hi,
it only happens with **twgames**?

If you open the workflow viewer in Alfred 3, there should be a **Run NSApple Script** that is connected to the **twgames**. 
Please try to change the "Alfred 2"-string in the **Run NSApple Script** to "Alfred 3".

Hope this helps :-)

**Comment by eusi** [comment]
If my last post fixes your issue, please try following code in the **Run NSApple Script** also:

```
on alfred_script(q)


-- use Alfred 3 if exists, otherwise Alfred 2


set doesAlfred3Exists to false
try
	do shell script "osascript -e 'id of app \"Alfred 3\"'"
	set doesAlfred3Exists to true
end try


if doesAlfred3Exists then
	tell application "Alfred 3" to search "twbygame " & q
else 
	tell application "Alfred 2" to search "twbygame " & q
end if


end alfred_script
```

Thank you in advance for testing.

**Comment by pedrokleiz** [comment]
Hi,

It only broke on twgames because it was a NSAppleScript (I believe).
Your script on the second post worked as well, so you can update the code on the workflow. :)

**Comment by pedrokleiz** [comment]
Actually, I fixed some problems I was having with Alfred 2 and it continues to be broken. So I started doing some testing on my own (even though I don't have much experience with NSAppleScript).
```
osascript -e 'id of app "Alfred 3"'
com.runningwithcrayons.Alfred-3
osascript -e 'id of app \"Alfred 3\"'
10:11: syntax error: Expected expression, property or key form, etc. but found unknown token. (-2741)
```

I fixed it but it's still breaking, probably something with the boolean or the if/else statement. So I just changed the string to Alfred 3, but if you want someone to test with Alfred 3 I can do it. :)

**Comment by cfriegel-tara** [comment]
Hi again,
ok, 2 things:

1st, your individual solution as Alfred3-user should be this (as content for the **NSAppleScript**):
```
on alfred_script(q)
    tell application "Alfred 3" to search "twbygame " & q
end alfred_script
```

2nd, to improve a more generic version, we need to make it work for Alfred 2 and 3.
So, as I understand, you say that my NSAppleScript from the 3rd post doesn't work properly? When you use the NSAppleScript, does it work for Alfred 3? What happens, when it doesn't work?

I tested on Alfred 2 only, it does work here.

**Comment by eusi** [comment]
Hi again,
ok, 2 things:

1st, your individual solution as Alfred3-user should be this (as content for the **NSAppleScript**):
```
on alfred_script(q)
    tell application "Alfred 3" to search "twbygame " & q
end alfred_script
```

2nd, to improve a more generic version, we need to make it work for Alfred 2 and 3.
So, as I understand, you say that my NSAppleScript from the 3rd post doesn't work properly? When you use the NSAppleScript, does it work for Alfred 3? What happens, when it doesn't work?

I tested on Alfred 2 only, it does work here.

**Comment by pedrokleiz** [comment]
Hi,

Trying switching to this:
`do shell script "osascript -e 'id of app "Alfred 2"'"`
And changing from false from true and vice-versa. Does it still work?

When I use your script with the try and the if/else it just doesn't open Alfred 3.

**Comment by eusi** [comment]
Hey,
without escaping the "-character it shouldn't work in an AppleScript, not at all. Without escaping it would just work in the terminal.

Actually the NSAppleScript from the 3rd post should be correct.... Have you renamed your Alfred3-application somehow for some reason?

Here are some code examples you could try to get more clarification what actually is not working:
1 Does this work for you, if you search with twgames and select a game then?
```
on alfred_script(q)
tell application "Alfred 3" to search "twbygame " & q
end alfred_script
```

2 Does this something for you?
```
on alfred_script(q)
tell application "Alfred 2" to search "twbygame " & q
end alfred_script
```

3 Does this work for you?
```
on alfred_script(q)
try
do shell script "osascript -e 'id of app \"Alfred 3\"'"
tell application "Alfred 3" to search "twbygame " & q
end try
end alfred_script
```

**Comment by snide** [comment]
@eusi I tested by changing the NSAppleScript tag (only) and it worked fine in Alfred 3.

If you haven't upgraded still, I'd be more than happy to paypal / bitcoin you a donation to purchase an upgrade. I use your plugin all the time and along with livestreamer it's such an awesome flow. Thanks so much for sharing it with the community.

**Comment by eusi** [comment]
@snide I am pleased to hear that you like it!
Oh, that is great! I added a paypal-donation button to https://github.com/eusi/alfred2-twitch-streamer for my paypal account me@eusi.de 
Thanks!

P.S. I will close this issue (validate by @snide). I will change the code structure in near future, so that you do not need to change the string any longer.
